
CFLAGS=-Wall

all: bin_search_stl bin_search_v1

bin_search_v1:
	g++ $(CFLAGS) bin_search_v1.cpp -o bin_search_v1.exe

bin_search_stl:
	g++ $(CFLAGS) bin_search_stl.cpp -o bin_search_stl.exe

clean:
	rm *.exe

